GSM/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^backend/', include('backend.urls')),
    url(r'^', include('web.urls')),
]

repository/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    """
    用户表
    """
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    email = models.EmailField(verbose_name='邮箱', unique=True)
    avatar = models.ImageField(verbose_name='头像')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

class Blog(models.Model):
    """
    博客信息
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题',max_length=64)
    site = models.CharField(verbose_name='个人博客前缀',max_length=32,unique=True)
    theme = models.CharField(verbose_name='博客主题',max_length=32)
    user = models.OneToOneField(to='UserInfo',to_field='nid',on_delete=models.CASCADE)

class Category(models.Model):
    """
    个人文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题',max_length=32)
    blog = models.ForeignKey(verbose_name='属于博客',to='Blog',to_field='nid',on_delete=models.CASCADE)

class ArticleDetail(models.Model):
    """
    文章详细
    """
    content = models.TextField(verbose_name='文章内容')
    article = models.OneToOneField(verbose_name='所属文章',to='Article',to_field='nid',on_delete=models.CASCADE)

class UpDown(models.Model):
    """
    文章顶或踩
    """
    article = models.ForeignKey(verbose_name='文章', to='Article', to_field='nid',on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='赞或踩用户', to='UserInfo', to_field='nid',on_delete=models.CASCADE)
    up = models.BooleanField(verbose_name='是否赞')

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]

class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

class Article(models.Model):
    """
        文章
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题',max_length=128)
    summary = models.CharField(verbose_name='文章简介',max_length=255)
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    creat_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)

    blog = models.ForeignKey(verbose_name='所属博客',to='Blog',to_field='nid',on_delete=models.CASCADE)
    category = models.ForeignKey(verbose_name='文章类型',to='Category',to_field='nid',on_delete=models.CASCADE)

    type_choices = [
        (1,'Python'),
        (2,'Linux'),
        (3,'C++'),
        (4,"架构师"),
    ]
    article_type_id = models.IntegerField(choices=type_choices,default=None)

    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )


class Article2Tag(models.Model):
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid',on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid',on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

web/views/home.py
from django.shortcuts import HttpResponse,render,redirect
from repository import models
from django.urls import reverse
from utils.pagination import Pagination

def index(request,*args,**kwargs):
    """
    博客首页
    :param request:
    :return:
    """
    article_type_list = models.Article.type_choices
    if kwargs:
        article_type_id = int(kwargs['article_type_id'])
        bass_url= reverse('index',kwargs=kwargs)
        print(bass_url)
    else:
        article_type_id=None
        bass_url='/'
    data_count = models.Article.objects.filter(**kwargs).count()
    if not data_count:
        data_count=1
    if article_type_id ==0:
        data_count = models.Article.objects.all().order_by('nid').count()
        page_obj = Pagination(request.GET.get('p'), data_count)
        article_list = models.Article.objects.all().order_by('nid')[page_obj.start:page_obj.end]
    else:
        page_obj = Pagination(request.GET.get('p'), data_count)
        article_list = models.Article.objects.filter(**kwargs).order_by('nid')[page_obj.start:page_obj.end]
    page_str = page_obj.page_str(bass_url)

    return render(
        request,
        'index.html',
        {
            'article_list':article_list,
            'article_type_list':article_type_list,
            'article_type_id':article_type_id,
            'page_str':page_str
        }
    )

def home(request,site):
    """
    个人首页
    :param request:
    :param site:
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/all/0.html')
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,date_format(creat_time,"%%Y-%%m") as ctime from repository_article group by date_format(creat_time,"%%Y-%%m")'
    )
    article_list = models.Article.objects.filter(blog=blog).order_by('nid').all()
    return render(
        request,
        'home.html',
        {
            'blog':blog,
            'tag_list':tag_list,
            'category_list':category_list,
            'date_list':date_list,
            'article_list':article_list
        }
    )

def filter(request,site,condition,val):
    """
    分类显示
    :param request:
    :param site:
    :param condition:
    :param val:
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/login')
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,date_format(creat_time,"%%Y-%%m") as ctime from repository_article group by date_format(creat_time,"%%Y-%%m")'
    )
    template_name = "home_summary_list.html"
    if condition =='tag':
        template_name='home_title_list.html'
        article_list = models.Article.objects.filter(tags=val,blog=blog).all()
    elif condition == 'category':
        article_list = models.Article.objects.filter(tags=val,blog=blog).all()
    elif condition == 'date':
        article_list = models.Article.objects.filter(blog=blog).extra(
            where=['date_format(creat_time,"%%Y-%%m")=%s'],params=[val,]).all()
    else:
        article_list=[]

    return render(
        request,
        template_name,
        {
            'blog':blog,
            'tag_list':tag_list,
            'category_list':category_list,
            'date_list':date_list,
            'article_list':article_list
        }
    )

def detail(request,site,nid):
    """
    博文详情
    :param request:
    :param site:
    :param nid:
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    tag_list = models.Tag.objects.filter(blog=blog)
    category = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,date_format(creat_time,"%%Y-%%m") as ctime from repository_article group by date_format(creat_time,"%%Y-%%m")'
    )
    article = models.Article.objects.filter(blog=blog,nid=nid).select_related('category','articledetail').first()
    return render(
        request,
        'home_detail.html',
        {
            'blog':blog,
            'category':category,
            'date_list':date_list,
            'article':article
        }
    )

templates/backend_article.html
{% extends 'backend_layout.html' %}
{% load search %}
{% block css %}
<style>
    .conditions a{
        display: inline-block;
        padding: 2px 5px;
        margin-left: 5px;
    }
    .conditions a.active{
        background-color: #b35215;
        color: #ffffff;
    }
</style>
{% endblock %}
{% block conent %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">文章列表</li>
    </ol>
    <div>

        <div style="border: 1px dashed #dddddd;padding: 8px;border-left: 3px solid #337ab7;">
            <i class="fa fa-search" aria-hidden="true"></i> 搜索条件
        </div>
        <div style="padding: 10px">
            <div class="conditions row clearfix" style="margin: 0;padding: 8px 0;">
                <div class="col-xs-1" style="text-align: right">
                    {% category_all arg_dict %}
                </div>
                <div class="col-xs-11">
                    {% category_combine category_list arg_dict %}
                </div>
            </div>
            <div class="conditions row clearfix" style="margin: 0;padding: 8px 0;">
                <div class="col-xs-1" style="text-align: right">
                    {% article_type_all arg_dict %}
                </div>
                <div class="col-xs-11">
                    {% article_type_combine type_list arg_dict %}
                </div>
            </div>
        </div>
        <div class="clearfix"
             style="height: 36px;line-height: 35px;padding: 0 15px;border-top: 1px solid #dddddd;background-color: #f1f0f0">
            <i class="fa fa-table" aria-hidden="true"></i>
            搜索文章({{ data_count }}篇)
            <a target="_blank" href="/backend/add-article.html" class="right"
               style="display: inline-block;padding:0 10px;background-color: #428bca;color: #ffffff;">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                创建新文章
            </a>
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>文章标题</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in result %}
                <tr nid="{{ row.nid }}">
                    <td><a href="/{{ row.blog.site }}/{{ row.nid }}.html">{{ row.title }}</a></td>
                    <td>
                        <a class="btn btn-danger btn-xs">
                            <i class="fa fa-times" aria-hidden="true"></i>
                            删除
                        </a>
                        |
                        <a class="btn btn-primary btn-xs" href="/backend/edit-article-{{ row.nid }}.html">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            编辑
                        </a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
               {{ page_str }}
            </ul>
        </div>
    </div>


{% endblock %}

{% block js %}

{% endblock %}

templates/backend_base_info.html
{% extends 'backend_layout.html' %}
{% block css %}
    <style>
        .form-horizontal .control-label {
            padding-top: 7px;
            margin-bottom: 0;
            text-align: right;
        }

        .avatar-container {
            height: 200px;
            width: 200px;
            padding: 2px;
            border: 1px solid #dddddd;
            position: relative;
        }

        .avatar-container img {
            height: 100%;
            width: 100%;
            border: 0;
            overflow: hidden;
        }

        .avatar-container .text {
            text-align: center;
        }

        .avatar-container .img-file {
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            opacity: 0;
            position: absolute;
            z-index: 102;
        }
    </style>
{% endblock %}
{% block conent %}
    <ol class="breadcrumb">
        <li><a href="#">用户管理</a> </li>
        <li class="active">用户信息</li>
    </ol>
    <div>
        <div class="row" style="position: relative;">
            <form class="form-horizontal">
                <div class="col-xs-12">
                    <div class="form-group">
                        <label class="col-xs-2 control-label">用户名:</label>

                        <div class="col-xs-5">
                            <p class="form-control-static">{{ current_username.username }}</p>
                        </div>
                    </div>
                    {% for row in email %}
                    <div class="form-group">
                        <label class="col-xs-2 control-label">邮箱：</label>

                        <div class="col-xs-5">

                                <p class="form-control-static">{{ row.email }}</p>

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="nickname" class="col-xs-2 control-label">昵称：</label>

                        <div class="col-xs-5">
                            <input type="text" class="form-control" id="nickname" value="{{ row.nickname }}" >
                        </div>
                    </div>
                    {% endfor %}
                    <div class="form-group">
                        <label for="blogUrl" class="col-xs-2 control-label">博客地址：</label>

                        <div class="col-xs-5">
                            <input type="text" class="form-control" id="blogUrl">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="blogTheme" class="col-xs-2 control-label">博客主题：</label>

                        <div class="col-xs-5">
                            <select id="blogTheme" class="form-control">
                                <option>默认主题</option>
                                <option>红色火焰</option>
                                <option>嘿嘿哈嘿</option>
                                <option>哈哈哈嘿哈</option>
                                <option>编不出来了</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="blogTitle" class="col-xs-2 control-label">博客标题内容：</label>

                        <div class="col-xs-8">
                            <textarea id="blogTitle" style="min-height: 100px" class="form-control"
                                      placeholder="来一杯鸡汤..."></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-offset-2 col-xs-10">
                            <button type="submit" class="btn btn-primary">保 存</button>
                        </div>
                    </div>

                </div>
            </form>
            <div style="position: absolute;" class="col-xs-offset-7 col-xs-5">
                <div class="avatar-container">
                    <iframe style="display: none;" id="upload_iframe" name="upload_iframe"></iframe>
                    <form method="POST" action="/backend/upload-avatar.html" enctype="multipart/form-data"
                          target="upload_iframe">
                        {% csrf_token %}
                        <img id="previewImg" origin="/static/imgs/avatar/default.png"
                             src="/static/imgs/avatar/default.png"
                             style="border-radius: 50%;">

                        <div class="text">点击图片更换(<a href="#">撤销</a>)</div>
                        <input id="avatarImg" name="avatar_img" type="file" class="img-file"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            bindChangeAvatar4();
        });

        function bindChangeAvatar1() {
            $('#avatarImg').change(function () {
                var file_obj = $(this)[0].files[0];
                $('#prevViewImg')[0].src = window.URL.createObjectURL(file_obj)
            })
        }

        function bindChangeAvatar2() {
            $('#avatarImg').change(function () {
                var file_obj = $(this)[0].files[0];
                var reader = new FileReader();
                reader.readAsDataURL(file_obj);
                reader.onload = function (e) {
                    $('#previewImg')[0].src = this.result;
                };
            })
        }

        function bindChangeAvatar3() {
            $('#avatarImg').change(function () {
                var file_obj = $(this)[0].files[0];
                var form = new FormData();
                form.add('img_upload', file_obj);

                $.ajax({
                    url: '',
                    data: form,
                    processData: false,  // tell jQuery not to process the data
                    contentType: false,  // tell jQuery not to set contentType
                    success: function (arg) {

                    }
                })
            })
        }

        function bindChangeAvatar4() {
            $('#avatarImg').change(function () {
                $(this).parent().submit();

                $('#upload_iframe').load(function () {
                    var iframeContents = this.contentWindow.document.body.innerText;
                    iframeContents = JSON.parse(iframeContents);
                    if (iframeContents.status) {
                        $('#previewImg').attr('src', '/' + iframeContents.data);
                    }
                })

            })
        }

    </script>
{% endblock %}

templates/backend_category.html
{% extends 'backend_layout.html' %}
{% block css %}

{% endblock %}
{% block conent %}
    <ol class="breadcrumb">
        <li><a href="#">分类管理</a></li>
        <li class="active">分类列表</li>
    </ol>
    <div>
        <div class="row" style="padding: 20px 5px;">
            <form class="form-horizontal">
                <div class="col-xs-12">
                    <div class="form-group">
                        <label class="col-xs-1 control-label">分类名称</label>

                        <div class="col-xs-3">
                            <input type="text" class="form-control" id="add_category" placeholder="请输入分类名称">
                        </div>
                        <div class="col-xs-3">
                            <input type="button" class="btn btn-primary" id="add_cate" value="添 加">
                        </div>
                        <div class="catetip"></div>
                    </div>
                </div>
            </form>
        </div>

        <div style="height: 35px;background-color: #f5f5f5;line-height: 35px;padding: 0 15px;">
            <i class="fa fa-table" aria-hidden="true"></i>
            标签列表
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>序号</th>
                <th>分类</th>
                <th>文章个数</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in date_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.title }}</td>
                    <td>{{ row.c }}</td>
                    <td>
                        <a >
                            <button type="button" class="btn btn-primary btn-xs" data-toggle="modal"
                                    data-target="#exampleModal" data-cate_id={{ row.nid }} id="edit_category"
                               cate_id={{ row.nid }}>编辑</button>
                        </a>
                        |
                        <a class="btn btn-danger btn-xs" id="del_category" cate_id={{ row.nid }}>
                            <i class="fa fa-times" aria-hidden="true"></i>
                            删除
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">New message</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="recipient-name" class="control-label">Recipient:</label>
                            <input type="text" class="form-control" id="recipient-name">
                        </div>
                        <div class="form-group">
                            <label for="message-text" class="control-label">Message:</label>
                            <textarea class="form-control" id="message-text"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Send message</button>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix" style="margin-top: 0">
        <ul class="pagination right" style="margin-top: 0">
            {{ page_str }}
        </ul>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/js/jquery-1.12.4.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.js"></script>
    <script>
        $('#add_cate').click(function () {
            var add_cate = $('#add_category').val();
            console.log(add_cate);
            $.ajax({
                url: 'backend/add_category/',
                type: 'POST',
                data: {
                    add_cate: add_cate,
                },
                success: function (data) {
                    if (data.statu == true) {
                        location.reload()
                    } else {
                        var a = data.res;
                        $('.catetip').html(a);
                    }
                    setTimeout(function () {
                        $('.catetip').html('');
                    }, 5000)
                }

            })
        });
        $('td #del_category').click(function () {
            var cate_id = $(this).attr('cate_id');
            $.ajax({
                url: 'backend/del_category/',
                type: 'POST',
                data: {
                    cate_id: cate_id,
                },
                success: function (data) {
                    console.log(data);
                    location.reload();
                }
            })
        });
        $('#exampleModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var recipient = button.data('cate_id') // Extract info from data-* attributes
            console.log(button)
            var modal = $(this)
            modal.find('.modal-title').text('New message to ' + recipient)
            modal.find('.modal-body input').val(recipient)
        })
    </script>
{% endblock %}

templates/backend_index.html
{% extends 'backend_layout.html' %}
{% block css %}

{% endblock %}
{% block conent %}
    <h1>欢迎登陆:{{ request.session.user_info.username }}</h1>
{% endblock %}
{% block js %}
{% endblock %}

templates/backend_layout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
    <link rel="stylesheet" href="/static/css/backend.css"/>
    {% block css %} {% endblock %}
</head>
<body>
<div class="pg-header">
    <div class="logo left" style="text-align: center;background-color: #1c5a9c;">
        <a href="#" style="color: #ffffff;font-size:30px;font-weight: bold;text-decoration: none">
            EasyStack
        </a>
    </div>

    <div class="left-menu left">
        <a class="menu-item" href="/index.html">博客首页</a>
    </div>

    <div class="right-menu right clearfix">

        <div class="user-info right">
            <a href="#" class="avatar">
                <img class="img-circle" src="/static/imgs/avatar/default.png">
            </a>

            <div class="more-info">
                <a href="#" class="more-item">个人信息</a>
                <a href="/logout.html" class="more-item">注销</a>
            </div>
        </div>

        <a class="user-menu right">
            消息
            <i class="fa fa-commenting-o" aria-hidden="true"></i>
            <span class="badge bg-success">2</span>
        </a>

        <a class="user-menu right">
            通知
            <i class="fa fa-envelope-o" aria-hidden="true"></i>
            <span class="badge bg-success">2</span>
        </a>

        <a class="user-menu right">
            任务
            <i class="fa fa-bell-o" aria-hidden="true"></i>
            <span class="badge bg-danger">4</span>
        </a>
    </div>

</div>
<div class="pg-body">
    <div class="menu">
        <a class="menu-item" href="/backend/article-0-0.html">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span>文章管理</span>
        </a>
        <a class="menu-item" href="/backend/category/0.html">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span>分类管理</span>
        </a>
        <a class="menu-item" href="/backend/tag.html">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span>标签管理</span>
        </a>
        <a class="menu-item" href="/backend/base-info.html">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span>个人信息</span>
        </a>
    </div>
    <div class="content">
        {% block conent %} {% endblock %}
    </div>
</div>
<script type="text/javascript" src="/static/js/jquery-1.12.4.js"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'home_layout.html' %}

{% block content %}
<div class="summary-list">
    {% for row in article_list %}
        <div class="summary-item">
            <a href="/{{ blog.site}}/{{ row.nid }}.html">{{ row.title }}</a>
        </div>
        <div class="summary-content">
            {{ row.summary }}
        </div>
        <div class="summary-footer">
            <span>{{ row.creat_time|date:"Y-m-d H:i:s" }}</span>
            <span>{{ row.user.nickname }}</span>
            <span>阅读{{ row.read_count }}</span>
            <a>评论{{ row.comment_count }}</a>
            <a href="#">编辑</a>
        </div>
    {% endfor %}
 </div>
</div>
{% endblock %}

templates/home_layout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/edmure.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
    <link rel="stylesheet" href="/static/css/row-avatar.css"/>
{#    <link rel="stylesheet" href="/static/css/theme/{{ blog.theme }}.css"/>#}
    <link rel="stylesheet" href="/static/css/theme/default.css"/>
    {% block css %}{% endblock %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap/js/bootstrap.js"></script>
</head>
<body>
<div class="pg-header">
    <div class="title">{{ blog.title }}</div>
    <div class="menu-list">
        <a class="menu-item" href="/index.html">首页</a>
        <a class="menu-item" href="/{{ blog.site }}.html">个人首页</a>
        <a class="menu-item" href="/backend/index.html" onclick="transmitOnclick(this)">管理</a>
    </div>
</div>
<div class="pg-body">
    <div class="body-menu">
        <div class="notice">
            <div class="notice-header">公告</div>
            <div class="notice-body">
                <ul>
                    <li>昵称：{{ blog.user.nickname }}</li>
                    <li>关注：{{ blog.user.f.count }}</li>
                    <li>邮箱：{{ blog.user.email }}</li>
                </ul>
                <div class="memo">
                    真实是人生的命脉，是一切价值的根基。
                </div>
            </div>
        </div>
        <div class="tags">
            <div class="tags-header">标签</div>
            <div class="tags-body">
                <ul>
                    {% for tag in tag_list %}
                        <li><a href="/{{ blog.site }}/tag/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="types">
            <div class="types-header">分类</div>
            <div class="types-body">
                <ul>
                    {% for tag in category_list %}
                        <li><a href="/{{ blog.site }}/category/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>
                    {% endfor %}
                </ul>

            </div>
        </div>
        <div class="dates">
            <div class="dates-header">时间</div>
            <div class="dates-body">
                <ul>
                    {% for tag in date_list %}
                        <li><a href="/{{ blog.site }}/date/{{ tag.ctime }}.html">{{ tag.ctime}}({{ tag.num}})</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">
        {% block content %}{% endblock %}
    </div>
</div>
    {% block js %}{% endblock %}
<script src="/static/js/jquery-1.12.4.js">
    function transmitOnclick() {

    }
</script>
</body>
</html>

templates/home_summary_list.html
{% extends 'home_layout.html' %}

{% block content %}
    <div class="summary-list">
        {% for row in article_list %}
            <div class="summary-item" style="border-bottom: 1px solid #dddddd;padding: 8px 0;">
                <div class="summary-title">
                    <a href="/{{ blog.site }}/{{ row.nid }}.html">{{ row.title }}</a>
                </div>
                <div class="summary-content">
                    {{ row.summary }}
                </div>
                <div class="summary-footer">
                    <span>{{ row.create_time|date:"Y-m-d H:i:s" }}</span>
                    <span>{{ row.user.nickname }}</span>
                    <span>阅读({{ row.read_count }})</span>
                    <a href="/backend/edit-article-{{ row.nid }}.html">编辑</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}